// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor dono da carteira. Só vendedor ativo entra na fila. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Nome do vendedor dono da carteira. Só vendedor ativo entra na fila. */
          vendedor: string;
          /** Ordem de ligação dentro da carteira do vendedor, do maior score para o menor. */
          ordem: number;
          /** Identificador do cliente, o mesmo de gold.dim_cliente. */
          cliente_id: number;
          /** Nome do cliente como o vendedor o conhece. */
          razao_social: string;
          /** Cidade do cliente. Serve para agrupar as visitas de um mesmo dia. */
          cidade: string;
          /** Unidade federativa do cliente. */
          uf: string;
          /** Probabilidade de o cliente fazer pedido nos próximos 7 dias, de 0 a 1. */
          score: number;
          /** Faixa do score em quartis: Fria, Morna, Quente, Muito quente. */
          faixa: string;
          /** Quanto o cliente gasta por pedido, em média, no histórico dele. */
          ticket_medio: number;
          /** Por que este cliente está na lista, escrito para o vendedor ler antes de discar. */
          motivo: string;
          /** O SKU da marca preferida que o cliente parou de comprar, com o saldo em estoque. */
          sugestao: string;
          /** Resultado da ligação: vendeu, vai_pensar, sem_interesse ou nao_atendeu. */
          retorno_status: string;
          /** O que o cliente disse, em texto livre, escrito pelo vendedor. */
          retorno_comentario: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType DOUBLE */
          auc: number;
          /** @sqlType BIGINT */
          versao: number;
          /** @sqlType BIGINT */
          ligacoes_registradas: number;
          /** @sqlType BIGINT */
          vendas: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor dono da carteira. Só vendedor ativo entra na fila. */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
